@baseUrl=http://localhost:1337

### Send form request
POST {{baseUrl}}/api/forms
Content-Type: application/json

{
  "name": "john", 
  "email": "john@gmail.com",
  "gRecaptchaToken": "12345"
}

### Send form data

POST {{baseUrl}}/api/forms-confirm
Content-Type: application/json

{
  "token": "e43e45ed96805333ec4492f4d54032afde02dff2f38606d7fa0a06a6bb4ad51f"
}
