@baseUrl=http://localhost:1337

### Send form request
POST {{baseUrl}}/api/forms
Content-Type: application/json

{
  "data": {
    "name": "john",
    "email": "john@gmail.com",
    "gRecaptchaToken": "8888"
 }
}

### Send form data

POST {{baseUrl}}/api/forms-confirm
Content-Type: application/json

{
  "data": {
    "token": "9784e55fd0979c9f32e9fdedbccba7cd7f716cdff8b1bf5a3fc2ed431a97e5a1"
  }
}
