@baseUrl=http://localhost:1337

### Send form request
POST {{baseUrl}}/api/forms
Content-Type: application/json

{
  "data": {
    "name": "john",
    "email": "john@gmail.com",
    "gRecaptchaToken": "12345"
 }
}

### Send form data

POST {{baseUrl}}/api/forms
Content-Type: application/json

{
  "data": {
    "token": "bba7429a70de4a060c1bb8abf3507354e7ba72436f84f223a715a0603c8f5e84"
  }
}
